### ISSUE TITLE
h5 support

### ISSUE THREAD

**Issue by AD-Aleksandrov** [zador-blood-stained/fel-mass-storage#1]
Hello!
I would like to create the same image for sun50i(h5) device. May someone help me? What is the easiest way to build this?

Thanks,
Aleksandr

**Comment by zador-blood-stained** [comment]
The main problem will be the FEL mode support for any arm64 target (A64, H5). I don't think FEL mode will work with SPL FIT u-boot and not sure if the "reset64" sunxi-fel option will work with the current u-boot tree.

**Comment by AD-Aleksandrov** [comment]
Thanks! I will try to find the solution.
