### ISSUE TITLE
A50 doesn't work

### ISSUE THREAD

**Issue by Fusseldieb** [zador-blood-stained/fel-mass-storage#6]
Trying it on an Allwinner A50 chip, following happens:

```
Connect device in FEL mode and press <Enter>

Warning: no 'soc_sram_info' data for your SoC (id=1755)

usb_bulk_send() ERROR -7: Operation timed out

```
Also, the tablet only has a NAND chip, no eMMC

**Comment by zador-blood-stained** [comment]
Sorry, this was made a long time ago for H3 devices with SD/eMMC only. Neither sunxi-tools nor used u-boot nor used kernel support A50 or NAND
